### ISSUE TITLE
Atom Feed broken

### ISSUE THREAD

**Issue by denisbrodbeck** [hankchizljaw/personal-site-hylia#9]
Hi Andy,

my feed reader just complained about your [website](https://hankchizljaw.com/).

I think you've got a weird character inside one of your [posts](https://github.com/hankchizljaw/personal-site-hylia/blob/master/src/posts/making-the-new-piccalilli-logo.md).

![image](https://user-images.githubusercontent.com/87793/81824713-15848380-9536-11ea-915d-fc47c5d80516.png)
![image](https://user-images.githubusercontent.com/87793/81824848-34831580-9536-11ea-9a8f-a6faa217150f.png)

Btw, thanks for your blog, I'm learning something new every time 😄

**Comment by hankchizljaw** [comment]
Ah thank you! I've fixed that now :)
